#!/bin/bash
mkdir ../exe
mkdir ../lib
mkdir ../pair
mkdir ../spec
cp exe/* ../exe/
cp spec/* ../spec/
cp Gemfile ../
cp Guardfile ../
cp .rspec ../
cp .gitignore ../
cd ..
bundle install
rm -rf pingpongpair
